
name: myapp
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.1+2

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  cloud_firestore: ^6.0.1
  provider: ^6.1.5+1
  google_fonts: ^6.3.1
  firebase_auth: ^6.0.2
  firebase_core: ^4.1.0
  image_picker: ^1.2.0
  intl: ^0.20.2
  firebase_storage: ^13.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
