name: moegyi
description: "A new Flutter project for MoeGyi."
publish_to: 'none'
version: 1.0.1+2

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  cloud_firestore: ^6.0.1
  provider: ^6.1.5+1
  google_fonts: ^6.3.1
  firebase_auth: ^6.0.2
  firebase_core: ^4.1.0
  image_picker: ^1.2.0
  intl: ^0.20.2
  firebase_storage: ^13.0.1
  image: ^4.5.4
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  url_launcher: ^6.3.2
  firebase_analytics: ^12.0.1
  carousel_slider: ^5.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.6

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/images/logo.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/images/
