// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-NvAQYtytzNWy0d2y95f6Q1xVec-4n-w',
    appId: '1:271385741888:android:13613504286b656a0b6da5',
    messagingSenderId: '271385741888',
    projectId: 'moegyishop-820a2',
    databaseURL: 'https://moegyishop-820a2-default-rtdb.firebaseio.com',
    storageBucket: 'moegyishop-820a2.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPu30SDETczr7gOjNSglDSHWYbMCuEnW4',
    appId: '1:271385741888:web:5dbd483d33e613cf0b6da5',
    messagingSenderId: '271385741888',
    projectId: 'moegyishop-820a2',
    authDomain: 'moegyishop-820a2.firebaseapp.com',
    databaseURL: 'https://moegyishop-820a2-default-rtdb.firebaseio.com',
    storageBucket: 'moegyishop-820a2.firebasestorage.app',
    measurementId: 'G-3XXE6JDK2V',
  );

}