// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCpxwrft4bVU3g2q2cGb-3TghMBPRp0Ms',
    appId: '1:405459867937:android:cded0bb72983e2d9420660',
    messagingSenderId: '405459867937',
    projectId: 'kzlshop',
    storageBucket: 'kzlshop.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAr0hjKEwOlzWPDGjDgHWwqmxZ9SqV_h30',
    appId: '1:405459867937:web:649bd2384a6ec739420660',
    messagingSenderId: '405459867937',
    projectId: 'kzlshop',
    authDomain: 'kzlshop.firebaseapp.com',
    storageBucket: 'kzlshop.firebasestorage.app',
    measurementId: 'G-21BMCWD2D9',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcSBc9XVUcPfl4i-k1xw7RdufRMNtritM',
    appId: '1:405459867937:ios:c9236942d29e5dd3420660',
    messagingSenderId: '405459867937',
    projectId: 'kzlshop',
    storageBucket: 'kzlshop.firebasestorage.app',
    androidClientId: '405459867937-bo3j3lfnm91ec11habdn837cc5rb3r84.apps.googleusercontent.com',
    iosClientId: '405459867937-hei7ab5su64umpgg5ak0g8alnmo94fri.apps.googleusercontent.com',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcSBc9XVUcPfl4i-k1xw7RdufRMNtritM',
    appId: '1:405459867937:ios:c9236942d29e5dd3420660',
    messagingSenderId: '405459867937',
    projectId: 'kzlshop',
    storageBucket: 'kzlshop.firebasestorage.app',
    androidClientId: '405459867937-bo3j3lfnm91ec11habdn837cc5rb3r84.apps.googleusercontent.com',
    iosClientId: '405459867937-hei7ab5su64umpgg5ak0g8alnmo94fri.apps.googleusercontent.com',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAr0hjKEwOlzWPDGjDgHWwqmxZ9SqV_h30',
    appId: '1:405459867937:web:85758b67ba842508420660',
    messagingSenderId: '405459867937',
    projectId: 'kzlshop',
    authDomain: 'kzlshop.firebaseapp.com',
    storageBucket: 'kzlshop.firebasestorage.app',
    measurementId: 'G-WD93GEBM8E',
  );

}